### ISSUE TITLE
Don't require any-promise if older versions of node

### ISSUE THREAD

**Issue by chartzoge** [heap/heap-node#5]
I've recently implemented heap-api server tracking, which works well with one caveat. If you are running nodejs < 0.12 (i'm running 0.10), any-promise fails to initialize thus causing heap-api to initialize. 

I propose: if a user is using a lower version of nodejs (0.10 or lower) then don't require in any-promise and fallback to the callback method. But, there should be an optional setting for this to say, "I'm using an older version of node, but I still want to use promise's."

Or: don't use any-promise at all and do all the detection within heap-api. I don't think there's any problem to heap-api requiring their own promise library by default.

**Comment by pwnall** [comment]
Hm, we have node 0.10 in [the Travis CI test matrix](https://travis-ci.org/heap/heap-node), and our code is passing the tests.

Did you install a promise library as described [here](https://github.com/heap/heap-node#promise-based-usage)?

**Comment by pwnall** [comment]
Also, if that's not the problem, can you please post the exception trace you're getting from any-promise?

Thank you!

**Comment by chasemellody** [comment]
Hey revisiting this. Node 0.10 is out of support. So let's close this :)
